### ISSUE TITLE
Kodi Official Repository Release Candidate

### ISSUE THREAD

**Issue by Lunatixz** [PseudoTV/PseudoTV_Live#6]
@PseudoTV/developers, @PseudoTV/project-managers, @PseudoTV/skinners

Goal of this .org is to improve, clean, and stabilize PseudoTV Live for Kodi's official repository.

Primary Mission:

PseudoTV Live is designed to be an all inclusive Kodi interface, skinnable and meant to function like a standard cable box.

PseudoTV Live already incorporates almost all aspects of Kodi: PVR, Local media, UPNP, HDhomerun, Plugins and Smart playlists...

I'd like to weed out code that may be rejected by team kodi, at the same time I would like to keep external metadata services ie. fyi television, trakt, schedules direct, fanarttv. Taking advantage of their paid services which requires access keys should be allowed?

Interface, code and skins can be improved... I'll post "issues" and assign jobs, feel free to contribute what and when you can... I appreciate everyone of you who took the time to join this project. Any files you contribute/edit, please feel free to place your name in the file header.

Thanks again

Kevin

**Comment by learningit** [comment]
Below is a response from Martijn to someone looking to add their addon to the Kodi repo. Does it impact what you want to do?

"we do not allow addons to pull in channels lists which can change without we knowing about it.
Since you host the channel list on your dropbox this can change without us checking.

regards,
Martijn Kaijser
XBMC Foundation"

**Comment by Lunatixz** [comment]
My lists are all hosted via github/PseudoTV_Lists, Only private data is from xmltv listings... and a few off site parsing... but thanks for the info.

**Comment by learningit** [comment]
Meaning that the lists are packaged with the addon or hosted as a "raw" on github? Sorry I haven't looked thru the whole thing yet - there's a fair bit to digest with your addon.

**Comment by Lunatixz** [comment]
Lists are parsed directly from github... not packed with addon.

**Comment by learningit** [comment]
The recent demise of DesiTV in the forum, I think is because the addon started out ok with a list (I think it was php) but the list became filled with ilive stuff over time.

**Comment by Lunatixz** [comment]
90% of the list is youtube/vimeo related, then there is LiveTV, InternetTV and Addons... 
if Kodi's team made their stance clear, I'd conform to their needs.

But IMO there is no difference between a plugin that parses a public list... and a plugin that parses a public website. Both have the potential to change without Kodis control.

**Comment by learningit** [comment]
I think there are at least three options: 1) move the lists into the addon; 2) host the lists in the kodi repo - there may be performance issues with this; or 3) move the lists to the appropriate service, e.g. create a vimeo list on vimeo, youtube list on youtube, etc. 
I would probably just ask what would be acceptable in the addon dev forum. There does seem to be a trend of removing even forum support threads for addons which have external list - TV on Desi Zone recently got binned - http://forum.kodi.tv/showthread.php?tid=238074

**Comment by Lunatixz** [comment]
You're comparing my plugin to one where the developer had intentioned on provide illegal content.

PseudoTV Live does not provide content, and the lists are harmless... have you taken a look? we are not talking about feeds hacking and stealing feeds from services... we are talking about legal feeds.

I do not believe the issue with PTVL getting into the repo has anything to do with the list. Lists are arbitrary, heck parsing any website, api is parsing a list... what matters is the content of the list. 

One of the reasons my code didn't make it in the repo was because of some binary code, which has been removed... I was using rtmpdump to check feeds... didn't know it couldn't be distributed.

Mistakes like that... is why I put this .org together... more minds and eyes to review code :)

I know we share the same values when it comes to providing legal services, so collaboration should be easy :+1:

**Comment by learningit** [comment]
No, you've got me totally wrong. I know what your addon is about, I'm pointing out that getting into the official repo is getting tougher because (again my opinion) there has been quite a bit of blowback after Ned (or Nate?) went after tvaddons in the forum. A lot of people complained about the arbitrary enforcement of the rules. Subsequently, a couple of the torrent addons got canned on the forum, etc. Looking at the response that Martijn gave about external lists, I tend to think that's a universal rule for the kodi repo. I don't think they're likely to make exceptions anymore because it has unfortunately ended badly in the past when they have. Again, there are ways around it.
In no way was I trying to imply that PTVL had any illegal content.

**Comment by Lunatixz** [comment]
True... You are making a valid point.. Community lists are such a small aspect of PTVL. I don't think we need to worry about it right now. Worst case we remove the lists.

**Comment by KODeKarnage** [comment]
FWIW, I once overcame an objection from Team Kodi about my addon cloning itself in the user's addons folder. At the time, the Team member said that the addon was not allowed to access any files outside of the addons folder. But I argued that the rules implied that it couldnt be done "behind the scenes", and that my function was not an automatic process and that I had added a yesno dialogue that informed the user about exactly what the addon would be doing and asked for their permission.

Since then this has been added to the rules regarding file access; "Exceptions to this rule may be granted in specific cases only. Please contact Team XBMC's add-on repository maintainers via the add-on mailing list if your add-on needs access to such files."

With this in mind, perhaps a solution is to have a hard-coded list submitted with the addon (and updated there only on version bumps), and then provide the user with the choice (during setup, on first-run, and in the Settings) of linking to your online curated|maintained version. You could even offer them the option of connecting to a different list if they wish, allowing them to fork it.

Naturally, this would allow the user to "revert" to the Kodi repo version of the list anytime they wanted.

I think the sticking point for Team Kodi is when addons force undesirable actions on Kodi. They dont have any problem with anything the USER chooses to do.

**Comment by shortusername** [comment]
@learningit do you think to avoid the whole issue of outside lists it may be possible to incorporate something in your add-ons that @Lunatixz can pull directly into PTVL if your add-on is detected as installed on the system? This will take away the need for maintaining a list and just pull the data directly from the add-on if installed with little to no user interaction other than installing your work from the official kodi repo?

**Comment by learningit** [comment]
I was actually thinking the same thing for my addons. I have implemented caching of show data in many of them for performance reasons. If you look at something like plugin.video.wnbc in the userdata there is a file called "shows.json" which contains some info about the show and it's episodes. I could expand that and add a plugin call to initialize/refresh the entire cache (currently it's on demand as a user navigates shows).  You would need to init the addon rather than just install, but that shouldn't be an issue.

**Comment by learningit** [comment]
Actually plugin.video.abcfamily is a better example because it caches episodes as well as shows.

**Comment by Lunatixz** [comment]
You guys need to browse the code... Plugin detection was added day one of this project.

**Comment by Lunatixz** [comment]
Sorry if I come off heated, but this is a major chip on my shoulder... I can't tell you how many users I deal with treat this plugin as some illegal plugin that is only around to provide crap...

Unfortunately so many illegal plugins use "lists" that you can't say or use that word without ppl thinking that's what's going on...

This conversion is focused way too much on something that I could just as easily drop.

**Comment by Lunatixz** [comment]
Final thought on the topic, PTVL is designed to function in the same manner as Kodi, it parses plugin content in the same way.

Once we start "requiring" plugins to provide "lists", there is nothing to stop illegal plugins from making their own lists... next thing... PTVL is no different than the aforementioned plugins.

My stance on piracy is the same as Kodis, I will not provide it, but there is nothing I can do to stop it.
PTVL will always function in the same manner as Kodi, if Kodi starts requiring special lists from plugins, then we will do the same... otherwise we are safest following Kodis methods.

**Comment by shortusername** [comment]
sooo... my wife is sick and can't sleep ... therefore I can't sleep. In my tossing and turning I got to thinking... can PTVL do a check to see if an add-on is in the official kodi repo and move fwd with the option to auto-populate from there? Thoughts?
